# backend/src/app/infrastructure/migrations/env.py

from logging.config import fileConfig

from alembic import context
from sqlalchemy import create_engine, pool

from src.app.core.base import Base
from src.app.core.config import settings


# ---------------------------------------------------------------------
# SAFE CONFIG ACCESSOR
# ---------------------------------------------------------------------
def get_config_safe():
    """Protects against env.py being imported during validation or tests."""
    try:
        return context.config
    except Exception:
        return None


# ---------------------------------------------------------------------
# FILTER RULES
# ---------------------------------------------------------------------
def include_object(obj, name, type_, reflected, compare_to):
    # Exclude version table only (not real schema tables)
    if (
        type_ == "table"
        and name == "alembic_version"
        and getattr(obj, "schema", None) in {"core", "acct", "inv", "pos"}
    ):
        return False
    return True


def process_revision_directives(context, revision, directives):
    """Remove autogenerated empty migration files."""
    if directives:
        script = directives[0]
        if script.upgrade_ops.is_empty():
            directives[:] = []


# ---------------------------------------------------------------------
# OFFLINE MODE
# ---------------------------------------------------------------------
def run_migrations_offline(cfg):
    # Use the same DB URL as the app (no config interpolation involved)
    url = settings.database_url

    context.configure(
        url=url,
        target_metadata=Base.metadata,
        literal_binds=True,
        include_schemas=True,
        # IMPORTANT: let Alembic create alembic_version in the default schema
        # so we don't require "core" to exist before 000000000001 runs.
        compare_type=True,
        compare_server_default=True,
        include_object=include_object,
        process_revision_directives=process_revision_directives,
        dialect_opts={"paramstyle": "named"},
    )

    with context.begin_transaction():
        context.run_migrations()


# ---------------------------------------------------------------------
# ONLINE MODE
# ---------------------------------------------------------------------
def run_migrations_online(cfg):
    # -----------------------------------------------------------------
    # Import ALL MODELS HERE (never at module import time)
    # -----------------------------------------------------------------
    import src.app.org.models.organization_models
    import src.app.org.models.role_models
    import src.app.org.models.user_models

    import src.app.accounting.models.account_models
    import src.app.accounting.models.bank_account_models
    import src.app.accounting.models.customer_balance_models
    import src.app.accounting.models.journal_models
    import src.app.accounting.models.journal_line_models

    import src.app.inventory.models.item_models
    import src.app.inventory.models.location_models
    import src.app.inventory.models.stock_level_models
    import src.app.inventory.models.stock_movement_models

    import src.app.pos.models.customer_models
    import src.app.pos.models.payment_models
    import src.app.pos.models.sale_models
    import src.app.pos.models.terminal_models
    import src.app.pos.models.tax_rate_models

    # Create engine using the same URL the app uses.
    # NOTE: no interpolation, no touching alembic.ini.
    engine = create_engine(
        settings.database_url,
        poolclass=pool.NullPool,
    )

    with engine.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=Base.metadata,
            include_schemas=True,
            # Again, no version_table_schema here — keep alembic_version
            # in the default schema so 000000000001 can create "core" first.
            compare_type=True,
            compare_server_default=True,
            include_object=include_object,
            process_revision_directives=process_revision_directives,
        )

        with context.begin_transaction():
            context.run_migrations()


# ---------------------------------------------------------------------
# ALEMBIC ENTRY POINT
# ---------------------------------------------------------------------
def run_migrations():
    cfg = get_config_safe()
    if cfg is None:
        return

    if cfg.config_file_name:
        fileConfig(cfg.config_file_name)

    if context.is_offline_mode():
        run_migrations_offline(cfg)
    else:
        run_migrations_online(cfg)


# ---------------------------------------------------------------------
# TRIGGER MIGRATIONS
# ---------------------------------------------------------------------
run_migrations()
